hmcts/wa-task-batch-service

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2124
axios 1.2.2, config 3.3.8 and tsconfig-paths 4.1.1
```
[ ] Yes
[x] No
```
> RWA-2124 - axios 1.2.2, config 3.3.8 and tsconfig-paths 4.1.1

- Jenkinsfile_CNP
removing deprecated code
```
[ ] Yes
[x] No
```
> RWA-2186 removing deprecated code

- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2191
-Fix the CVE problem of cookie jar
```
[ ] Yes
[X] No
```
> RWA-2191 Fix CVE problem of cookiejar

- Dockerfile
- README.md
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2566
Upgrade to node v.18.17
```
[ ] Yes
[ x] No
```
> Upgrade to node v.18.17

- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2796
Update dependency qs to v6.11.2 
Update dependency nodemon to v2.0.22
```
[ ] Yes
[x ] No
```
> RWA-2796: Renovate upgrades

- charts/wa-task-batch-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2845
Migrating to Workload Identity
```
[ ] Yes
[x] No
```
> RWA-2845 Migrating to Workload Identity

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-2882
```
[ ] Yes
[ ] No
```
> RWA-2882: Excluding helmet from auto upgrading by renovate

- charts/wa-task-batch-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2912
Charts upgrade
```
[ ] Yes
[ x ] No
```
> RWA-2912: chart upgrade

- charts/wa-task-batch-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-3073
Upgrade Helm chart to 2.1.1
```
[ ] Yes
[x] No
```
> RWA-3073 job helm upgrade

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3176
Fix dependency check failure
```
[ ] Yes
[ x ] No
```
> RWA-3176: axios upgrade

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3203
```
[ ] Yes
[ x] No
```
> RWA-3203: Upgrade express.js

- .dependabot/config.yml
https://tools.hmcts.net/jira/browse/RWA-3246
```
[ ] Yes
[X] No
```
> RWA-3246: Remove Dependabot

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3301
```
[ ] Yes
[x ] No
```
> RWA-3301: Update formidable

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3416
```
[ ] Yes
[x] No
```
> RWA-3416: Upgrade CVEs

- .github/renovate.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3665
```
[ ] Yes
[ x] No
```
> RWA-3665: Reconfigure renovate PRs

- charts/wa-task-batch-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-3735
```
[ ] Yes
[ x] No
```
> RWA-3735: Upgrade job to 2.1.2

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3808
dependency updates including transitive dependencies
```
[ ] Yes
[x] No
```
> RWA-3808 - dependency updates

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3898
update cookie package
```
[ ] Yes
[x] No
```
> RWA-3898 -- cookie update

- .dockerignore
- Dockerfile
https://tools.hmcts.net/jira/browse/RWA-4168 
```
[ ] Yes
[ ] No
```
> RWA-4168: Corepack build fix

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4195
Upgrading axios to latest version
```
[ ] Yes
[x] No
```
> RWA-4195: Upgrading axios to latest version

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4239
Removed request dependency
```
[ ] Yes
[x] No
```
> RWA-4239: removed request

- package.json
- yarn-audit-known-issues
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4433
Resolved CVE issues
```
[ ] Yes
[x] No
```
> RWA-4433: Resolved nightly CVE

- README.md
- src/test/routes/home.ts
https://tools.hmcts.net/jira/browse/RWA-4469 
```
[ ] Yes
[ ] No
```
> RWA-4469: Routes tests fix

- README.md
- src/test/routes/home.ts
Reverts hmcts/wa-task-batch-service#580
> Revert "RWA-4469: Routes tests fix"

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4526
Upgraded superagent
Bumped supertest out of deprecated version
```
[ ] Yes
[x] No
```
> RWA-4526: Upgrade superagent
